//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UTES.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_UTES_FORM                   101
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_UTESTYPE                    129
#define IDD_UTES_PREF                   130
#define IDI_ICON1                       133
#define IDI_ICON2                       134
#define IDI_ICON3                       135
#define IDI_ICON4                       136
#define IDD_DIALOG_GROUP                139
#define IDD_DIALOG_SCALE                144
#define IDD_DIALOG_EXPONENT             147
#define IDD_UTES_WEIGHT                 151
#define IDI_ICON5                       153
#define IDB_BITMAP3                     154
#define IDR_MENU_PREF                   155
#define IDD_DIALOG_OPTIONS              156
#define IDB_SPLASH2                     157
#define IDD_DIALOG_EXP_ADV              158
#define IDD_DIALOG_SELPR                161
#define IDD_DIALOG_AUTO_SCALE           162
#define IDD_DIALOG_ROBAST               163
#define IDD_UTES_POINT                  164
#define IDC_TREE                        1000
#define IDC_LIST_CRIT                   1003
#define IDC_LIST_GRUP                   1005
#define IDC_COMBO_X                     1007
#define IDC_COMBO_Y                     1008
#define IDC_LIST_VAL                    1009
#define IDC_SPIN                        1014
#define IDC_BUDDY_SPIN                  1015
#define IDC_SLIDER1                     1017
#define IDC_EDIT_GOD                    1018
#define IDC_EDIT1                       1023
#define IDC_EDIT2                       1024
#define IDC_LIST1                       1025
#define IDC_LIST2                       1026
#define IDC_EDIT3                       1026
#define IDC_BUTTON1                     1027
#define IDC_EDIT4                       1027
#define IDC_BUTTON2                     1028
#define IDC_EDIT_CRNAME                 1030
#define IDC_STATIC_PF                   1031
#define IDC_STATIC_CR                   1032
#define IDC_STATIC_SCALE                1034
#define IDC_STATIC_FACE                 1036
#define IDC_COMBO_TYPE                  1037
#define IDC_EDIT_TERM                   1038
#define IDC_BUTTON_DEFAULT              1039
#define IDC_BUTTON_NEXT_EXP             1042
#define IDC_EDIT_NAME                   1043
#define IDC_BUTTON_CHARACT              1045
#define IDC_COMBO_SCALE                 1046
#define IDC_BUTTON_SCALE                1047
#define IDC_BUTTON_ADV                  1048
#define IDC_COMBO_METHOD                1049
#define IDC_EDIT_FORMAT                 1050
#define IDC_STATIC_FBORDER              1051
#define IDC_CHECK_RANG                  1052
#define IDC_STATIC_P2                   1053
#define IDC_STATIC_P1                   1054
#define IDC_EDIT_GNAME                  1056
#define IDC_MSFLEXGRID                  1057
#define IDC_CHECK2                      1059
#define IDC_SUM_W                       1060
#define IDC_EDIT_G                      1061
#define IDC_MSFLEXGRID1                 1062
#define IDC_STATIC_VER                  1064
#define IDC_COMBO1                      1065
#define IDC_LIST_METHODS                1066
#define IDC_EDIT_MIN                    1067
#define IDC_EDIT_MAX                    1068
#define IDC_EDIT_STEP                   1069
#define IDC_BUTTON_AUTO                 1070
#define IDC_BUTTON_OPTIONS              1071
#define IDC_RADIO1                      1072
#define IDC_RADIO2                      1073
#define IDC_MYGRID                      1076
#define IDC_BUTTON3                     1077
#define IDC_RADIO3                      1078
#define IDC_STATIC4                     1079
#define IDC_BUTTON4                     1080
#define IDC_BUTTON5                     1081
#define IDC_BUTTON6                     1082
#define IDC_EXP_GROUP                   1086
#define ID_VIEW_CRITERIA                32771
#define ID_VIEW_PREF                    32772
#define ID_DELGR                        32774
#define ID_CHCR                         32775
#define ID_CHGR                         32777
#define ID_DELCR                        32778
#define ID_ADDGR                        32779
#define ID_ADDCR                        32780
#define ID_                             32781
#define ID_BUTTON_ADD_CR                32783
#define ID_BUTTON_ADD_GR                32784
#define ID_BUTTON_EXCEl                 32794
#define ID_MENUITEM_COPY                32796
#define ID_MENUITEM_INSERT              32797
#define ID_MENUITEM_APPROX              32798
#define ID_MENUITEM_CLEAR               32799
#define ID_MENUITEM_DECL                32801
#define ID_MENUITEM_INCL                32802
#define ID_MENUITEM_ISALL               32807
#define ID_BUTTON_CHANGE_VIEW           32808
#define ID_MENUITEM_SETUP               32811
#define ID_MENUITEM_IMPORT              32815
#define ID_MENUITEM_UNDO                32816
#define ID_BUTTON_LOADFM                32817
#define ID_MENUITEM_SELMETH             32818
#define ID_MENUITEM_SHOWGRAD            32820
#define ID__TEST                        32821
#define ID_ACCELERATOR32822             32822
#define ID_NEXT_EXP                     32822

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
